/* bitbit, a bitboard based chess engine written in c.
 * Copyright (C) 2022-2024 Isak Ellmer
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <string.h>

#include "nnue.h"
#include "util.h"
#include "io.h"
#include "nnuefile.h"

alignas(64) static ft_weight_t ft_weights[K_HALF_DIMENSIONS * FT_IN_DIMS];
alignas(64) static ft_bias_t ft_biases[K_HALF_DIMENSIONS];

alignas(64) static ft_weight_t psqt_weights[FT_IN_DIMS];

alignas(64) static weight_t hidden1_weights[16 * FT_OUT_DIMS];
alignas(64) static bias_t hidden1_biases[16];

alignas(64) static weight_t hidden2_weights[32 * 16];
alignas(64) static bias_t hidden2_biases[32];

alignas(64) static weight_t output_weights[1 * 32];
alignas(64) static bias_t output_biases[1];

int main(int argc, char **argv) {
	int i;

	if (argc != 2) {
		printf("usage: %s file\n", argv[0]);
		return 1;
	}
	FILE *f = fopen(argv[1], "rb");
	if (!f) {
		fprintf(stderr, "error: failed to open file %s\n", argv[1]);
		return 2;
	}
	
	if ((i = nnuefile(f, ft_weights, ft_biases,
			psqt_weights, hidden1_weights,
			hidden1_biases, hidden2_weights,
			hidden2_biases, output_weights,
			output_biases))) {
		if (i == 2)
			fprintf(stderr, "error: wrong nnue version\n");
		else
			fprintf(stderr, "error: failed to read nnue weights\n");
		return 3;
	}

	FILE *g = fopen("src/nnueweights.c", "w");
	if (!g) {
		fprintf(stderr, "error: failed to open file src/nnueweights.c\n");
		return 4;
	}
	fprintf(g, "/* This file has been autogenerated by weightbit. */\n\n");
	fprintf(g, "#include <stdint.h>\n#include <stdalign.h>\n\n#include \"nnue.h\"\n\n");

	fprintf(g, "alignas(64) ft_weight_t builtin_ft_weights[K_HALF_DIMENSIONS * FT_IN_DIMS] = {");
	for (i = 0; i < K_HALF_DIMENSIONS * FT_IN_DIMS; i++) {
		if (i % 32 == 0)
			fprintf(g, "\n");
		fprintf(g, "%d,", ft_weights[i]);
	}
	fprintf(g, "\n};\n\n");
	fprintf(g, "alignas(64) ft_bias_t builtin_ft_biases[K_HALF_DIMENSIONS] = {");
	for (i = 0; i < K_HALF_DIMENSIONS; i++) {
		if (i % 32 == 0)
			fprintf(g, "\n");
		fprintf(g, "%d,", ft_biases[i]);
	}
	fprintf(g, "\n};\n\n");
	fprintf(g, "alignas(64) ft_weight_t builtin_psqt_weights[FT_IN_DIMS] = {");
	for (i = 0; i < FT_IN_DIMS; i++) {
		if (i % 32 == 0)
			fprintf(g, "\n");
		fprintf(g, "%d,", psqt_weights[i]);
	}
	fprintf(g, "\n};\n\n");
	fprintf(g, "alignas(64) weight_t builtin_hidden1_weights[16 * FT_OUT_DIMS] = {");
	for (i = 0; i < 16 * FT_OUT_DIMS; i++) {
		if (i % 32 == 0)
			fprintf(g, "\n");
		fprintf(g, "%d,", hidden1_weights[i]);
	}
	fprintf(g, "\n};\n\n");
	fprintf(g, "alignas(64) bias_t builtin_hidden1_biases[16] = {");
	for (i = 0; i < 16; i++) {
		if (i % 32 == 0)
			fprintf(g, "\n");
		fprintf(g, "%d,", hidden1_biases[i]);
	}
	fprintf(g, "\n};\n\n");
	fprintf(g, "alignas(64) weight_t builtin_hidden2_weights[32 * 16] = {");
	for (i = 0; i < 32 * 16; i++) {
		if (i % 32 == 0)
			fprintf(g, "\n");
		fprintf(g, "%d,", hidden2_weights[i]);
	}
	fprintf(g, "\n};\n\n");
	fprintf(g, "alignas(64) bias_t builtin_hidden2_biases[32] = {");
	for (i = 0; i < 32; i++) {
		if (i % 32 == 0)
			fprintf(g, "\n");
		fprintf(g, "%d,", hidden2_biases[i]);
	}
	fprintf(g, "\n};\n\n");

	fprintf(g, "alignas(64) weight_t builtin_output_weights[1 * 32] = {");
	for (i = 0; i < 1 * 32; i++) {
		if (i % 32 == 0)
			fprintf(g, "\n");
		fprintf(g, "%d,", output_weights[i]);
	}
	fprintf(g, "\n};\n\n");
	fprintf(g, "alignas(64) bias_t builtin_output_biases[1] = {");
	for (i = 0; i < 1; i++) {
		if (i % 32 == 0)
			fprintf(g, "\n");
		fprintf(g, "%d,", output_biases[i]);
	}
	fprintf(g, "\n};\n");

	return (fclose(g) || fclose(f)) * 5;
}
